spring.datasource.url=jdbc:postgresql://localhost:11228/featuredb
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=audit
spring.datasource.password=audit

spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
